Models/AuthPageModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace razor.Pages;
using razor.Models;
using razor.Services;
public class AuthPageModel : PageModel
{
    public User CurrUser { get; set; } = new User();
    public bool MessageExists { get; set; } = false;
    public string Message { get; set; } = "";
    public virtual void OnGet()
    {
        Session? s = SessionService.Get((string)this.HttpContext.Items["SessionCookie"]);
        CurrUser = AuthentificationService.Get(s.UserId);
    }
    public void OnPostLogOut()
    {
        AuthentificationService.LogOutUser((string)this.HttpContext.Items["SessionCookie"]);
        this.HttpContext.Response.Redirect("/");
    }
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - razor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/razor.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-page="/Index">Tournaments list</a>
                        </li>
                    </ul>
                    @if (Model.CurrUser == null)
                    {
                        <a class="nav-link text-dark" asp-page="/Login" style="float: right;">Login</a>
                    }
                    else
                    {
                        <span style="float: right; display: contents;">
                            <span>Hi @Model.CurrUser.Username</span>
                            <form method="post" asp-page-handler="LogOut">
                                <button class="btn">Log out</button>
                            </form>
                        </span>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @if (@Model.MessageExists)
    {
        <script defer>
            alert("@Model.Message");
        </script>
    }
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>