Models/Tournament.cs
using System.ComponentModel.DataAnnotations;
using razor.Services;
namespace razor.Models;
public class Tournament
{
    public int Id { get; set; }
    public TournamentState State { get; set; } = TournamentState.Scheduled;
    public bool GroupStage { get; set; } = false;
    public int NumberOfGroupWinners { get; set; } = 2;
    public int NumberOfPlayersInGroup { get; set; } = 4;
    public IList<Competitor> Competitors { get; set; } = new List<Competitor>();
    public IList<Group> Groups { get; set; } = new List<Group>();
    public int FinishedGroups { get; set; } = 0;
    public IList<LadderStage> Ladder { get; set; } = new List<LadderStage>();
    public int FinishedLadderStages { get; set; } = 0;
    public Competitor? Winner { get; set; }
    [Required]
    public string Name { get; set; } = string.Empty;
    public bool AddCompetitor(Competitor newCompetitor)
    {
        if (State != TournamentState.Scheduled)
            return false;
        Competitors.Add(newCompetitor);
        newCompetitor.AddTournament(this);
        return true;
    }
    public bool CreateGroups()
    {
        if (State != TournamentState.Scheduled || GroupStage == false)
            return false;
        State = TournamentState.GroupsPending;
        char name = 'A';
        List<Competitor> allCompetitors = new(Competitors);
        Random random = new Random();
        while (allCompetitors.Count > 0)
        {
            Group g = new Group { Name = name, Tournament = this };
            for (int i = 0; i < NumberOfPlayersInGroup && allCompetitors.Count > 0; i++)
            {
                Competitor c = allCompetitors[random.Next(allCompetitors.Count)];
                allCompetitors.Remove(c);
                g.Competitors.Add(new CompPoint(c, 0));
            }
            g.CreateMatches();
            g = GroupService.Add(g);
            Groups.Add(g);
            name++;
        }
        return true;
    }
    public void GroupFinished()
    {
        if (FinishedGroups >= Groups.Count)
            return;
        FinishedGroups++;
        if (FinishedGroups == Groups.Count)
        {
            State = TournamentState.GroupsFinished;
        }
    }
    public bool CreateLadder()
    {
        if (GroupStage && State != TournamentState.GroupsFinished || GroupStage == false && State != TournamentState.Scheduled)
            return false;
        State = TournamentState.Ladder;

        List<Competitor>? allCompetitors;
        if (GroupStage == true)
        {
            allCompetitors = new List<Competitor>();
            foreach (Group group in Groups)
            {
                for (int i = 0; i < NumberOfGroupWinners && i < NumberOfPlayersInGroup; i++)
                    allCompetitors.Add(group.Competitors[i].Competitor); // looking for all competitors who takes part in the ladder
            }
        }
        else
            allCompetitors = new(Competitors);

        int k = 2;
        while (k < allCompetitors.Count)
            k *= 2;
        while (k > 1)
        {
            Ladder.Add(new LadderStage(k, this)); // creating blank ladderStages
            k /= 2;
        }

        Random random = new Random();
        k = 0;
        while (allCompetitors.Count > 0)
        {
            Competitor c = allCompetitors[random.Next(allCompetitors.Count)];
            allCompetitors.Remove(c);
            Ladder[0].SetCompetitor(c, k);
            k++;
        }
        Ladder[0].SetActive();
        return true;
    }
    public void PromoteToNextLadderStage(Competitor competitor, LadderStage stage, int position)
    {
        int s = Ladder.IndexOf(stage) + 1;
        if (s < Ladder.Count)
            Ladder[s].SetCompetitor(competitor, position);
        else
            Winner = competitor;
    }
    public void LadderStageFinished()
    {
        if (FinishedLadderStages >= Ladder.Count)
            return;
        FinishedLadderStages++;
        if (FinishedLadderStages == Ladder.Count)
            State = TournamentState.Finished;
        else
        {
            LadderStage? ls = Ladder.FirstOrDefault(l => l.MatchesPlayed == 0, null);
            if(ls != null)
                ls.SetActive();
        }
            
    }
}

public enum TournamentState { Scheduled, GroupsPending, GroupsFinished, Ladder, Finished }

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace razor.Pages;
using razor.Models;
using razor.Services;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : AuthPageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public override void OnGet()
    {
        Session? s = SessionService.Get((string)this.HttpContext.Items["SessionCookie"]);
        CurrUser = AuthentificationService.Get(s.UserId);
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace razor.Pages;
using razor.Models;
using razor.Services;

public class IndexModel : AuthPageModel
{
    private readonly ILogger<IndexModel> _logger;
    public List<Tournament> Tournaments { get; set; } = new List<Tournament>();
    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }
    public override void OnGet()
    {
        Session? s = SessionService.Get((string)this.HttpContext.Items["SessionCookie"]);
        CurrUser = AuthentificationService.Get(s.UserId);

        Tournaments = TournamentService.GetAll();
    }
}

Pages/Tournament.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using razor.Models;
using razor.Services;

namespace razor.Pages
{
    public class TournamentModel : PageModel
    {
        public User CurrUser { get; set; } = new User();
        public bool MessageExists { get; set; } = false;
        public string Message { get; set; } = "";
        [BindProperty]
        public Tournament? Tournament { get; set; }
        public void OnGet(string tournament_name)
        {
            Session? s = SessionService.Get((string)HttpContext.Items["SessionCookie"]);
            CurrUser = AuthentificationService.Get(s.UserId);
            Tournament = TournamentService.Get(tournament_name);
        }
        public void OnPostStartGroups(string tournament_name)
        {
            Tournament = TournamentService.Get(tournament_name);
            MessageExists = true;
            if (Tournament == null)
            {
                Message = "Error. Groups couldn't be created";
                return;
            }
            if (Tournament.CreateGroups())
                Message = "Groups created";
            else
                Message = "Error. Groups couldn't be created";
        }
        public void OnPostSetWinner(int match_id, int match_winner_id, string tournament_name)
        {
            Match? match = MatchService.Get(match_id);
            Competitor? match_winner = CompetitorService.Get(match_winner_id);
            if (match == null || match_winner == null)
            {
                MessageExists = true;
                Message = "Error";
            }
            else
                match.SetWinner(match_winner);
            OnGet(tournament_name);
        }
        public void OnPostStartLadder(string tournament_name)
        {
            Tournament = TournamentService.Get(tournament_name);
            MessageExists = true;
            if (Tournament == null)
            {
                Message = "Error. Ladder couldn't be created";
                return;
            }
            if (Tournament.CreateLadder())
                Message = "Ladder created";
            else
                Message = "Error. Ladder couldn't be created";
        }
        public void OnPostLogOut()
        {
            AuthentificationService.LogOutUser((string)this.HttpContext.Items["SessionCookie"]);
            this.HttpContext.Response.Redirect("/");
        }
    }
}

Pages/add_tournament.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Web;

namespace razor.Pages;
using razor.Models;
using razor.Services;
public class add_tournamentModel : AuthPageModel
{
    public List<Competitor> Competitors { get; set; } = new List<Competitor>();
    [BindProperty]
    public Tournament NewTournament { get; set; } = new Tournament();
    [BindProperty]
    public int[] NewCompetitorsIds { get; set; } = Array.Empty<int>();
    public override void OnGet()
    {
        Session? s = SessionService.Get((string)this.HttpContext.Items["SessionCookie"]);
        CurrUser = AuthentificationService.Get(s.UserId);
        if (CurrUser == null || CurrUser.Role == UserRole.User)
            this.HttpContext.Response.Redirect("/error");
        Competitors = CompetitorService.GetAll();
    }
    public IActionResult OnPost()
    {
        if (!ModelState.IsValid)
            return Page();
        foreach (int competitorId in NewCompetitorsIds)
        {
            Competitor competitor = CompetitorService.Get(competitorId);
            if(competitor != null)
                NewTournament.AddCompetitor(competitor);
        }
        if (TournamentService.Add(NewTournament) == null)
        {
            MessageExists = true;
            Message = "Tournament with this name currently exists.";
            return Page();
        }

        return Redirect("/");
    }
}

Pages/login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using razor.Models;
using razor.Services;

namespace razor.Pages
{
    public class loginModel : AuthPageModel
    {
        [BindProperty]
        public User loginUser { get; set; } = new User();
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
                return Page();
            if(AuthentificationService.LoginUser((string)this.HttpContext.Items["SessionCookie"], loginUser))
                return Redirect("/");
            return Page();
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@using razor.Models
@{
    ViewData["Title"] = "List of tournaments";
}

<div class="text-center">
    <h1>Tournaments list</h1>
    <ul style="padding: 0px; list-style: none;">
        @foreach (Tournament tournament in Model.Tournaments)
        {
            <li><a asp-page="/Tournament" asp-route-tournament_name="@tournament.Name">@tournament.Name</a></li>
        }
        @if (Model.Tournaments.Count() == 0)
        {
            <li>No tournaments to display</li>
        }
    </ul>
    @if (Model.CurrUser != null && Model.CurrUser.Role != Models.UserRole.User)
    {
        <a class="nav-link text-dark" asp-area="" asp-page="/add_tournament" style="background-color: green; color: white !important; display: inline;">Add tournament</a>
    }
</div>

Pages/Tournament.cshtml
@page
@model razor.Pages.TournamentModel
@using razor.Models
@{
    ViewData["Title"] = "List of tournaments";
}
@section Styles {
    <style>
        .green {
            background-color: green;
            color: white;
            border-radius: 0px;
        }

            .green:hover {
                color: white;
            }

        .winner {
            color: green;
        }

        .loser {
            color: red;
        }

        table {
            margin-left: auto;
            margin-right: auto;
        }

            table td, table th {
                border: 1px solid black;
                padding: 5px;
            }

        ul {
            list-style: none;
        }

        form {
            display: inline-block;
        }

        h3 {
            margin-top: 20px;
        }

        .set_winner_btn {
            text-decoration: underline;
            color: darkblue;
            padding: 0px;
            border: none;
        }

        .ladder_match {
            padding: 10px;
        }

        .ladder_competitor {
            border: 1px solid black;
            height: 26px;
        }
    </style>
}
    <div class="text-center">
        <h1>@Model.Tournament.Name</h1>
        <h2><a id="competitors_head" href="javascript:ShowCompetitors();">Competitors</a></h2>
        <ul class="d-none" id="competitors_list">
            @foreach (Competitor competitor in Model.Tournament.Competitors)
        {
            <li>@competitor.FullName</li> <!--competitors list-->
        }
    </ul>
    @if (Model.CurrUser != null && Model.CurrUser.Role != UserRole.User && Model.Tournament.GroupStage == true && Model.Tournament.State == TournamentState.Scheduled)
    {
        <form method="post" asp-page-handler="StartGroups" asp-route-tournament_name="@Model.Tournament.Name">
            <button class="btn green">Create groups</button> <!--create groups button-->
        </form>
    }
    @if (Model.Tournament.State != TournamentState.Scheduled && Model.Tournament.GroupStage == true)
    {
        <h2><a id="groups_head" href="javascript:ShowGroups();">Groups</a></h2> <!--groups list-->
        <ul class="d-none" id="groups_list">
            @foreach (Group group in Model.Tournament.Groups)
            {
                <li>
                    <h3>Group @group.Name</h3>
                    <div style="display: inline-block; width: 40%; float: right;">
                        <h4>Table</h4>
                        <table>
                            <tr>
                                <th scope="col">Competitor</th>
                                <th scope="col">Points</th>
                            </tr>
                            @foreach (CompPoint competitor in group.Competitors)
                            {
                                <tr>
                                    <td>@competitor.Competitor.FullName</td>
                                    <td>@competitor.Points</td>
                                </tr>
                            }
                        </table>
                    </div>
                    <div style="display: inline-block; width: 55%;float:left;">
                        <h4>Matches</h4>
                        <ul class="matches">
                            @foreach (Match match in group.Matches)
                            {
                                <li class="match">
                                    @if (match.Played == false && Model.CurrUser != null && Model.CurrUser.Role != UserRole.User)
                                    {
                                        <form method="post" asp-page-handler="SetWinner" asp-route-match_id="@match.Id" asp-route-match_winner_id="@match.FirstCompetitor.Id" asp-route-tournament_name="@Model.Tournament.Name">
                                            <button class="btn set_winner_btn">Mark as winner</button>
                                        </form>
                                    }
                                    @if (match.Played && match.Winner)
                                    {
                                        <span class="winner competitor">@match.FirstCompetitor.FullName</span>
                                    }
                                    else if (match.Played && match.Winner == false)
                                    {
                                        <span class="loser competitor">@match.FirstCompetitor.FullName</span>
                                    }
                                    else
                                    {
                                        <span class="competitor">@match.FirstCompetitor.FullName</span>
                                    }
                                    <span>-</span>
                                    @if (match.Played && match.Winner)
                                    {
                                        <span class="loser competitor">@match.SecondCompetitor.FullName</span>
                                    }
                                    else if (match.Played && match.Winner == false)
                                    {
                                        <span class="winner competitor">@match.SecondCompetitor.FullName</span>
                                    }
                                    else
                                    {
                                        <span class="competitor">@match.SecondCompetitor.FullName</span>
                                    }
                                    @if (match.Played == false && Model.CurrUser != null && Model.CurrUser.Role != UserRole.User)
                                    {
                                        <form method="post" asp-page-handler="SetWinner" asp-route-match_id="@match.Id" asp-route-match_winner_id="@match.SecondCompetitor.Id" asp-route-tournament_name="@Model.Tournament.Name">
                                            <button class="btn set_winner_btn">Mark as winner</button>
                                        </form>
                                    }
                                </li>
                            }
                        </ul>
                    </div>
                    <div style="clear: both;"></div>
                </li>
            }
        </ul>
    }
    @if ((Model.Tournament.State == TournamentState.GroupsFinished && Model.Tournament.GroupStage == true && Model.CurrUser != null && Model.CurrUser.Role != UserRole.User) || (Model.Tournament.State == TournamentState.Scheduled && Model.Tournament.GroupStage == false && Model.CurrUser != null && Model.CurrUser.Role != UserRole.User))
    {
        <form method="post" asp-page-handler="StartLadder" asp-route-tournament_name="@Model.Tournament.Name">
            <button class="btn green">Create ladder</button> <!--create ladder button-->
        </form>
    }
    @if (Model.Tournament.State == TournamentState.Ladder || Model.Tournament.State == TournamentState.Finished)
    {
        <h2><a id="ladder_head" href="javascript:HideLadder();">Ladder</a></h2> <!--ladder-->
        <div id="ladder_list">
            @foreach (LadderStage ladderStage in Model.Tournament.Ladder)
            {
                <div style="width: calc( 100% / @Model.Tournament.Ladder.Count); float: left;">
                    @foreach (Match match in ladderStage.Matches)
                    {
                        <div class="ladder_match">
                            <div class="ladder_competitor">
                                @if (match.Played == false && Model.CurrUser != null && Model.CurrUser.Role != UserRole.User && ladderStage.Active)
                                {
                                    <form method="post" asp-page-handler="SetWinner" asp-route-match_id="@match.Id" asp-route-match_winner_id="@match.FirstCompetitor.Id" asp-route-tournament_name="@Model.Tournament.Name">
                                        <button class="btn set_winner_btn">Mark as winner</button>
                                    </form>
                                }
                                @if (match.FirstCompetitor.FullName == " ")
                                {
                                    <span>-</span>
                                }
                                else
                                {
                                    @if (match.Played && match.Winner)
                                    {
                                        <span class="winner">@match.FirstCompetitor.FullName</span>
                                    }
                                    else if(match.Played && match.Winner == false)
                                    {
                                        <span class="loser">@match.FirstCompetitor.FullName</span>
                                    }
                                    else
                                    {
                                        <span>@match.FirstCompetitor.FullName</span>
                                    }
                                }
                            </div>
                            <div class="ladder_competitor">
                                @if (match.Played == false && Model.CurrUser != null && Model.CurrUser.Role != UserRole.User && ladderStage.Active)
                                {
                                    <form method="post" asp-page-handler="SetWinner" asp-route-match_id="@match.Id" asp-route-match_winner_id="@match.SecondCompetitor.Id" asp-route-tournament_name="@Model.Tournament.Name">
                                        <button class="btn set_winner_btn">Mark as winner</button>
                                    </form>
                                }
                                @if (match.SecondCompetitor.FullName == " ")
                                {
                                    <span>-</span>
                                }
                                else
                                {
                                    @if (match.Played && match.Winner)
                                    {
                                        <span class="loser">@match.SecondCompetitor.FullName</span>
                                    }
                                    else if(match.Played && match.Winner == false)
                                    {
                                        <span class="winner">@match.SecondCompetitor.FullName</span>
                                    }
                                    else
                                    {
                                        <span>@match.SecondCompetitor.FullName</span>
                                    }
                                }
                            </div>
                        </div>
                    }
                </div>
            }
            <div style="clear: both;"></div>
        </div>
    }
    @if (Model.Tournament.State == TournamentState.Finished)
    {
        <h2>Tournament winner</h2>
        <h3>@Model.Tournament.Winner.FullName</h3>
    }
</div>

@section Scripts {
    <script>
        const competitors_list = document.getElementById("competitors_list");
        const competitors_head = document.getElementById("competitors_head");
        const groups_list = document.getElementById("groups_list");
        const groups_head = document.getElementById("groups_head");
        const ladder_list = document.getElementById("ladder_list");
        const ladder_head = document.getElementById("ladder_head");
        function ShowCompetitors() {
            competitors_list.classList.remove("d-none");
            competitors_head.setAttribute("href", "javascript:HideCompetitors();");
        }
        function HideCompetitors() {
            competitors_list.classList.add("d-none");
            competitors_head.setAttribute("href", "javascript:ShowCompetitors();");
        }
        function ShowGroups() {
            groups_list.classList.remove("d-none");
            groups_head.setAttribute("href", "javascript:HideGroups();");
        }
        function HideGroups() {
            groups_list.classList.add("d-none");
            groups_head.setAttribute("href", "javascript:ShowGroups();");
        }
        function ShowLadder() {
            ladder_list.classList.remove("d-none");
            ladder_head.setAttribute("href", "javascript:HideLadder();");
        }
        function HideLadder() {
            ladder_list.classList.add("d-none");
            ladder_head.setAttribute("href", "javascript:ShowLadder();");
        }
    </script>
}

Pages/add_tournament.cshtml
@page
@model razor.Pages.add_tournamentModel
@{
    ViewData["Title"] = "Add new tournament";
}
@using razor.Models
@section Styles {
    <style>
        .row label {
            width: 300px;
            text-align: left;
        }
        .row input, .row select {
            width: auto;
        }
        .row input, .row label {
            line-height: 24px;
            height: 24px;
        }
        .row button {
            width: 300px;
            margin-left: calc(100% - 320px);
        }
        div.line {
            margin: 10px 0px;
            border-bottom: 1px solid grey;
        }
        .green {
            background-color: green;
        }
    </style>
}
    <div class="text-center">
        <form method="post" class="card p-3">
        <div>
            <div asp-validation-summary="All"></div>
        </div>
        <div class="form-group mb-0 align-middle">
            <div class="row">
                <label asp-for="NewTournament.Name">tournament name</label>
                <input asp-for="NewTournament.Name" class="mr-5" />
            </div>
            <div class="line"></div>
            <div class="row">
                <label asp-for="NewTournament.GroupStage">tournament with group stage</label>
                <input asp-for="NewTournament.GroupStage" />
            </div>
            <div class="row">
                <label asp-for="NewTournament.NumberOfPlayersInGroup">group size</label>
                <input asp-for="NewTournament.NumberOfPlayersInGroup" disabled />
            </div>
            <div class="row">
                <label asp-for="NewTournament.NumberOfGroupWinners">number of competitors who progress from the group stage</label>
                <input asp-for="NewTournament.NumberOfGroupWinners" disabled />
            </div>
            <div class="line"></div>
            <div class="row">
                <label asp-for="NewCompetitorsIds">competitors</label>
                <select asp-for="NewCompetitorsIds">
                    @foreach (Competitor competitor in Model.Competitors)
                    {
                        <option value="@competitor.Id">@competitor.FullName</option>
                    }
                </select>

            </div>
            <div class="row">
                <button class="btn btn-primary">Create tournament</button>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    <script>
        const groupStageCheckbox = document.getElementById("NewTournament_GroupStage");
        const numberOfPlayersInGroupInput = document.getElementById("NewTournament_NumberOfPlayersInGroup");
        const numberOfGroupWinnersInput = document.getElementById("NewTournament_NumberOfGroupWinners");

        groupStageCheckbox.addEventListener('change', GroupsChanged);

        function GroupsChanged(event) {
            if (groupStageCheckbox.checked) {
                GroupsEnabled();
            }
            else {
                GroupsDisabled();
            }
        }

        function GroupsEnabled() {
            numberOfPlayersInGroupInput.removeAttribute('disabled');
            numberOfGroupWinnersInput.removeAttribute('disabled');
        }

        function GroupsDisabled() {
            numberOfPlayersInGroupInput.setAttribute('disabled', '');
            numberOfGroupWinnersInput.setAttribute('disabled', '');
        }
    </script>
}

Pages/login.cshtml
@page
@using razor.Models
@model razor.Pages.loginModel
@{
    ViewData["Title"] = "Login";
}

<h1>log in</h1>
<form method="post" class="card p-3">
    <div class="row">
        <div asp-validation-summary="All"></div>
    </div>
    <div class="form-group mb-0 align-middle">
        <label asp-for="loginUser.Username">Username</label>
        <input type="text" asp-for="loginUser.Username" class="mr-5">
        <label asp-for="loginUser.Password">Password</label>
        <input type="password" asp-for="loginUser.Password" class="mr-5">
        <button class="btn btn-primary">log in</button>
    </div>
</form>

@section Scripts {
<partial name="_ValidationScriptsPartial" />
}